alter table public.fish_species
  add column if not exists description_tr text,
  add column if not exists habitat_tr text,
  add column if not exists best_season_tr text,
  add column if not exists bait_tr text;

create unique index if not exists fish_species_name_tr_key on public.fish_species (name_tr);

insert into public.badge_definitions (slug, name_tr, description_tr, xp_reward, category)
values
  ('twentyfive_species', 'Fishdex Avcısı', '25 farklı tür yakala', 350, 'species'),
  ('fifty_species', 'Usta Kolleksiyoncu', '50 farklı tür yakala', 700, 'species'),
  ('fishdex_master', 'Fishdex Master', 'Fishdex içindeki 80 türü de keşfet', 1200, 'species')
on conflict (slug) do update set
  name_tr = excluded.name_tr,
  description_tr = excluded.description_tr,
  xp_reward = excluded.xp_reward,
  category = excluded.category;

insert into public.fish_species (
  name_tr,
  name_en,
  name_scientific,
  category,
  description_tr,
  habitat_tr,
  best_season_tr,
  bait_tr,
  is_active
)
values
  ('Levrek', 'Sea Bass', 'Dicentrarchus labrax', 'deniz', 'Kıyı avcılığının en popüler yırtıcılarından biridir.', 'Liman ağızları, taşlık kıyılar, lagünler ve akıntılı geçişler.', 'İlkbahar ve sonbahar.', 'Minnow, silikon, kaşık ve canlı yem.', true),
  ('Çipura', 'Gilthead Sea Bream', 'Sparus aurata', 'deniz', 'Sert vuruşlarıyla tanınan güçlü bir sparid türüdür.', 'Kumluk koylar, yosunlu zeminler, iskele çevresi ve sığ meralar.', 'İlkbahar sonu ve yaz başı.', 'Karides, mamun, sülünez ve dip takımları.', true),
  ('Lüfer', 'Bluefish', 'Pomatomus saltatrix', 'deniz', 'Hızlı saldıran sürü avcısı bir yırtıcıdır.', 'Boğaz geçişleri, akıntı hatları ve yem balığı yoğun bölgeler.', 'Sonbahar ve erken kış.', 'Rapala, kaşık, çapari üstü yem ve canlı yem.', true),
  ('Palamut', 'Bonito', 'Sarda sarda', 'göç', 'Sürüler halinde gezen hızlı pelajik avcıdır.', 'Açık su, boğaz geçişleri ve kıyıdan uzak yem balığı sürüleri.', 'Sonbahar başı.', 'Çapari, kaşık ve çekili takımlar.', true),
  ('Sazan', 'Carp', 'Cyprinus carpio', 'tatlı_su', 'Tatlı su avcılığının klasik ve güçlü balığıdır.', 'Göller, barajlar, sakin akarsular ve sazlık kıyılar.', 'İlkbahar sonu ile sonbahar arası.', 'Hamur, mısır, boilie ve dip yemleri.', true),
  ('Alabalık', 'Trout', 'Salmo trutta', 'tatlı_su', 'Soğuk ve oksijenli sularda yaşayan çevik bir av balığıdır.', 'Dağ dereleri, serin çaylar ve göl çıkışları.', 'İlkbahar ve sonbahar.', 'Spinner, küçük kaşık, silikon ve canlı böcek.', true),
  ('Mercan', 'Common Pandora', 'Pagellus erythrinus', 'deniz', 'Dipte gezen, sofralık değeri yüksek bir türdür.', 'Kayalık ve kumluk karışık tabanlar, ılıman kıyı meraları.', 'Yaz ve sonbahar.', 'Karides, sülünez ve hafif dip takımları.', true),
  ('Kefal', 'Flathead Grey Mullet', 'Mugil cephalus', 'deniz', 'Tedbirli yapısı nedeniyle dikkat isteyen kıyı balığıdır.', 'Limanlar, dere ağızları, lagünler ve sakin kıyılar.', 'Yaz sonu ve sonbahar.', 'Ekmek, hamur, yosun taklidi ve hafif şamandıra takımı.', true),
  ('Sudak', 'Zander', 'Sander lucioperca', 'tatlı_su', 'Gece ve loş saatlerde aktifleşen dişli bir tatlı su yırtıcısıdır.', 'Baraj gölleri, derin kıyılar ve taşlık drop-off bölgeleri.', 'İlkbahar sonu ve sonbahar.', 'Silikon shad, jig ve canlı yem.', true),
  ('Orkinos', 'Bluefin Tuna', 'Thunnus thynnus', 'göç', 'Çok güçlü açık deniz avcısıdır ve sportif açıdan üst seviyededir.', 'Açık su, derin pelajik hatlar ve yem balığı sürüleri.', 'Yaz ve sonbahar.', 'Çekili takımlar, popper ve canlı yem.', true),
  ('Turna', 'Northern Pike', 'Esox lucius', 'tatlı_su', 'Ani saldırılarıyla bilinen pusucu bir avcıdır.', 'Sazlık kıyılar, göl kenarları ve bitkili durgun sular.', 'İlkbahar sonu ve sonbahar.', 'Büyük kaşık, jerkbait, spinnerbait ve canlı yem.', true),
  ('Yayın', 'Wels Catfish', 'Silurus glanis', 'tatlı_su', 'Büyük boylara ulaşabilen dipte gezen güçlü bir yırtıcıdır.', 'Derin çukurlar, baraj dipleri ve ağır akıntı dışı bölgeler.', 'Yaz geceleri ve sıcak dönemler.', 'Canlı yem, ciğer, kalamar ve ağır dip takımları.', true),
  ('İstavrit', 'Horse Mackerel', 'Trachurus mediterraneus', 'deniz', 'Sürü gezen ve kıyıdan da sık avlanan hareketli bir türdür.', 'İskeleler, liman içleri, ışık alan bölgeler ve orta su.', 'Yıl boyu, özellikle sonbahar.', 'Çapari, küçük metal jig ve kurt takımı.', true),
  ('Karagöz', 'Two-banded Seabream', 'Diplodus vulgaris', 'deniz', 'Kayalık dipte gezen sert vuruşlu bir sparid türüdür.', 'Kayalık kıyılar, mendirekler ve yosunlu taşlıklar.', 'İlkbahar ve sonbahar.', 'Karides, mamun ve hafif dip takımları.', true),
  ('Sargoz', 'White Seabream', 'Diplodus sargus', 'deniz', 'Taşlık bölgelerde dolaşan mücadeleci bir kıyı balığıdır.', 'Kırmalık zeminler, kayalık burunlar ve köpüklü kıyılar.', 'İlkbahar ve sonbahar.', 'Karides, yengeç, mamun ve dip yemleri.', true),
  ('Ispari', 'Annular Seabream', 'Diplodus annularis', 'deniz', 'Sürü halinde gezen küçük ama keyifli av veren sparid türüdür.', 'Çayırlar, kumluk zeminler ve liman çevreleri.', 'Yaz ve sonbahar.', 'Kurt, karides ve hafif dip takımları.', true),
  ('Sarpa', 'Salema Porgy', 'Sarpa salpa', 'deniz', 'Otçul beslenmeye yakın yapısıyla sürü gezen kıyı balığıdır.', 'Posidonia çayırları, taşlık sığlıklar ve sakin koylar.', 'Yaz dönemi.', 'Yosun, ekmek ve hafif iğneli takımlar.', true),
  ('Mırmır', 'Striped Seabream', 'Lithognathus mormyrus', 'deniz', 'Kumluk zeminde dolaşan ince ama seri vuruşlu bir dip balığıdır.', 'Kumluk plajlar, hafif dalgalı kıyılar ve sığ meralar.', 'Yaz sonu ve sonbahar.', 'Mamun, sülünez ve ince dip takımları.', true),
  ('Barbun', 'Red Mullet', 'Mullus barbatus', 'deniz', 'Dipte gezen ve hassas takım gerektiren değerli bir türdür.', 'Yumuşak dipler, kumlu çamurlu alanlar ve kıyı meraları.', 'Yaz ve sonbahar.', 'Karides, kurt ve dip sürütmeleri.', true),
  ('Tekir', 'Striped Red Mullet', 'Mullus surmuletus', 'deniz', 'Kayalık karışık tabanlarda rastlanan dip gezer türdür.', 'Taş-kum karışık bölgeler ve kırmalı dipler.', 'Yaz sonu ve sonbahar.', 'Karides, kurt ve hassas dip takımları.', true),
  ('Sinarit', 'Dentex', 'Dentex dentex', 'deniz', 'Derin kayalıklarda yaşayan kuvvetli bir avcıdır.', 'Resif çevresi, derin taşlıklar ve sualtı yükseltileri.', 'İlkbahar sonu ve sonbahar.', 'Canlı yem, jig ve ağır dip takımları.', true),
  ('Fangri', 'Red Porgy', 'Pagrus pagrus', 'deniz', 'Derin meralarda gezen iri sparid türlerinden biridir.', 'Derin çakıllı zeminler, kayalık dipler ve açık kıyı hatları.', 'İlkbahar ve sonbahar.', 'Canlı karides, kalamar ve dip takımı.', true),
  ('Akya', 'Greater Amberjack', 'Seriola dumerili', 'deniz', 'Çok sert mücadele veren hızlı açık su yırtıcısıdır.', 'Açık deniz yapıları, batıklar ve derin akıntı hatları.', 'Yaz sonu ve sonbahar.', 'Jig, popper ve canlı yem.', true),
  ('Uskumru', 'Mackerel', 'Scomber scombrus', 'göç', 'Sürü gezen ve hızlı aksiyon veren pelajik türdür.', 'Açık kıyılar, geçiş hatları ve orta su kolonları.', 'Sonbahar ve kış başı.', 'Çapari, küçük metal yemler ve tüy takımları.', true),
  ('Kolyoz', 'Chub Mackerel', 'Scomber colias', 'göç', 'Uskumruya benzer şekilde sürü halinde av verir.', 'Açık kıyılar, liman dışları ve akıntılı su katmanları.', 'Yaz sonu ve sonbahar.', 'Çapari ve küçük metal yemler.', true),
  ('Zargana', 'Garfish', 'Belone belone', 'deniz', 'Yüzeye yakın dolaşan uzun yapılı hızlı bir av balığıdır.', 'Yüzey hattı, sakin koylar ve akıntılı kıyılar.', 'İlkbahar sonu ve yaz.', 'Şamandıralı takım, küçük sahteler ve tüy.', true),
  ('Tirsi', 'Twaite Shad', 'Alosa fallax', 'göç', 'Göç dönemlerinde sürü halinde görülen pelajik türdür.', 'Dere ağızları, boğaz hatları ve kıyı geçişleri.', 'İlkbahar göçü.', 'Çapari, küçük kaşık ve tüy takımları.', true),
  ('Kalkan', 'Turbot', 'Scophthalmus maximus', 'deniz', 'Dipte yatan ama güçlü kalkış yapan değerli bir flatfish türüdür.', 'Kumlu ve çamurlu zeminler, özellikle Karadeniz kıyıları.', 'Kış sonu ve ilkbahar.', 'Canlı yem, teke ve dip takımı.', true),
  ('Dil Balığı', 'Common Sole', 'Solea solea', 'deniz', 'Gece aktifleşen taban balığıdır.', 'İnce kumlu dipler ve sakin koylar.', 'İlkbahar ve sonbahar.', 'Kurt, karides ve dip yemleri.', true),
  ('Mezgit', 'Whiting', 'Merlangius merlangus', 'deniz', 'Soğuk sezonlarda verimli av sunan dip-gezer sürü balığıdır.', 'Orta derinlikte kumlu ve çamurlu dipler.', 'Kış ve ilkbahar.', 'Kurt, kalamar ve dip takımları.', true),
  ('Bakalyaro', 'European Hake', 'Merluccius merluccius', 'deniz', 'Derin sularda yaşayan avcı bir dip balığıdır.', 'Derin çamurlu dipler ve açık deniz hatları.', 'İlkbahar ve sonbahar.', 'Kalamar, şerit yem ve ağır dip takımları.', true),
  ('Lahoz', 'White Grouper', 'Epinephelus aeneus', 'deniz', 'Kaya diplerinde saklanan iri yırtıcılardandır.', 'Derin resifler, kovuklu kayalıklar ve kırmalar.', 'Yaz ve sonbahar.', 'Canlı yem, jig ve dip sırtısı.', true),
  ('Orfoz', 'Dusky Grouper', 'Epinephelus marginatus', 'deniz', 'Resif ve mağara çevresinde pusu kuran büyük bir avcıdır.', 'Kayalık mağaralar, dik drop-off bölgeleri ve resifler.', 'Yaz sonu ve sonbahar.', 'Canlı yem ve ağır dip takımları.', true),
  ('Trança', 'Goldblotch Grouper', 'Epinephelus costae', 'deniz', 'Derin kayalıkta av veren grouper grubundan bir türdür.', 'Kayalık tabanlar, kırmalar ve resif kenarları.', 'Yaz ve sonbahar.', 'Canlı yem, kalamar ve jig.', true),
  ('Hani', 'Comber', 'Serranus cabrilla', 'deniz', 'Küçük kayalık alanlarda sık rastlanan hareketli bir türdür.', 'Taşlık dipler, iskele ayakları ve resif başlangıçları.', 'Yaz boyunca.', 'Karides, kurt ve küçük silikonlar.', true),
  ('Eşkina', 'Brown Meagre', 'Sciaena umbra', 'deniz', 'Gece avcılığında öne çıkan taş dip balığıdır.', 'Mağaralı kayalıklar, mendirek dipleri ve koy içleri.', 'Yaz geceleri ve sonbahar.', 'Karides, mamun ve dip yemleri.', true),
  ('Lipsoz', 'Shi Drum', 'Umbrina cirrosa', 'deniz', 'Kumlukla taşlığın kesiştiği alanlarda gezen bir dip türüdür.', 'Kumlu koylar, kırma başlangıçları ve hafif dalgalı kıyılar.', 'İlkbahar sonu ve yaz.', 'Mamun, sülünez ve dip yemleri.', true),
  ('Minekop', 'Meagre', 'Argyrosomus regius', 'deniz', 'Güçlü kafa darbeleriyle tanınan büyük bir kıyı avcısıdır.', 'Dere ağızları, lagünler, derin koylar ve kıyı şevleri.', 'Yaz ve sonbahar.', 'Canlı yem, büyük silikon ve dip sırtısı.', true),
  ('Trakonya', 'Greater Weever', 'Trachinus draco', 'deniz', 'Dipte saklanarak pusu kuran bir türdür.', 'Kumluk tabanlar ve sığ kıyı meraları.', 'Yaz dönemi.', 'Dip sürütme, karides ve kurt.', true),
  ('Kırlangıç', 'Tub Gurnard', 'Chelidonichthys lucerna', 'deniz', 'Dipte gezen ama kalkışı sert olan renkli bir türdür.', 'Çamurlu ve kumlu dipler, açık kıyı alanları.', 'İlkbahar ve sonbahar.', 'Kalamar, karides ve dip yemleri.', true),
  ('İskorpit', 'Black Scorpionfish', 'Scorpaena porcus', 'deniz', 'Kayalık dipte kamufle olan sabırlı bir pusu avcısıdır.', 'Taş dip, mendirek içi ve kayalık koylar.', 'Yıl boyu.', 'Karides, küçük balık parçaları ve dip takımı.', true),
  ('Fener Balığı', 'Monkfish', 'Lophius piscatorius', 'deniz', 'Derin dipte yaşayan iri başlı pusu balığıdır.', 'Derin çamurlu dipler ve açık deniz şevleri.', 'Soğuk sezonlar.', 'Dip sırtısı ve ağır yemli takım.', true),
  ('Kılıç Balığı', 'Swordfish', 'Xiphias gladius', 'göç', 'Açık denizde yüksek mücadele sunan prestijli bir türdür.', 'Pelajik derin sular ve açık deniz geçişleri.', 'Yaz sonu ve sonbahar.', 'Çekili takım ve büyük yapay yemler.', true),
  ('Kupes', 'Bogue', 'Boops boops', 'deniz', 'Sürü gezen ve kıyıdan kolay av veren bir Akdeniz türüdür.', 'Kayalık kıyılar, liman çevresi ve yosunlu alanlar.', 'Yaz ve sonbahar.', 'Ekmek, kurt ve hafif dip/şamandıra takımları.', true),
  ('İzmarit', 'Picarel', 'Spicara smaris', 'deniz', 'Kıyıdan sık yakalanan küçük sürü balıklarındandır.', 'Sığ taşlıklar, çayırlar ve liman dışları.', 'İlkbahar ve yaz.', 'Kurt, ekmek ve küçük iğneli takımlar.', true),
  ('Melanur', 'Saddled Seabream', 'Oblada melanura', 'deniz', 'Sürüler halinde gezen dikkatli bir kıyı türüdür.', 'Taşlık koylar, çayırlar ve orta su.', 'Yaz ve erken sonbahar.', 'Ekmek, küçük silikon ve hafif iğneli takım.', true),
  ('Sokar', 'Dusky Spinefoot', 'Siganus luridus', 'deniz', 'Sıcak sularda yayılan ve otlanan yapıda bir kıyı balığıdır.', 'Kaya ve alg kaplı sığlıklar, liman ağızları.', 'Yaz boyunca.', 'Yosun, ekmek ve ince takım.', true),
  ('Lambuka', 'Dolphinfish', 'Coryphaena hippurus', 'göç', 'Yüzeyde avlanan çok hızlı açık su balığıdır.', 'Açık deniz yüzey hatları ve sürüklenen cisim çevresi.', 'Yaz sonu ve sonbahar.', 'Popper, casting jig ve çekili takım.', true),
  ('Grida', 'Golden Grouper', 'Epinephelus costae', 'deniz', 'Kaya yapılarında saklanan güçlü bir dip yırtıcısıdır.', 'Derin resifler ve kovuklu taşlık dipler.', 'Yaz ve sonbahar.', 'Canlı yem ve jig.', true),
  ('Kuzu Balığı', 'Axillary Seabream', 'Pagellus acarne', 'deniz', 'Orta boy sparid grubunda lezzetli ve seri vuruşlu bir türdür.', 'Kumlu-çakıllı dipler ve açık kıyı meraları.', 'İlkbahar ve sonbahar.', 'Karides, kurt ve dip takımı.', true),
  ('Berlam', 'Forkbeard', 'Phycis phycis', 'deniz', 'Derin dipte yaşayan gececi bir av balığıdır.', 'Taşlık derin dipler ve yarıklı alanlar.', 'Kış ve ilkbahar.', 'Kalamar ve şerit yem.', true),
  ('Pisi Balığı', 'Flounder', 'Platichthys flesus', 'deniz', 'Dipte kamufle olan düz balık türlerindendir.', 'Hafif çamurlu kumluk tabanlar ve nehir ağızları.', 'Kış sonu ve ilkbahar.', 'Kurt, teke ve dip takımı.', true),
  ('Kayabalığı', 'Goby', 'Gobius niger', 'deniz', 'Kaya ve iskele çevresinde yaşayan küçük dip türüdür.', 'Kayalıklar, iskele dipleri ve liman içleri.', 'Yıl boyu.', 'Kurt ve küçük dip takımları.', true),
  ('Zurna Balığı', 'Cornetfish', 'Fistularia commersonii', 'deniz', 'Uzun gövdeli, kıyı boyunca dolaşan avcı türdür.', 'Sığ resifler, kayalık kıyılar ve çayırlar.', 'Yaz ve sonbahar.', 'Küçük minnow ve silikon.', true),
  ('Müren', 'Moray Eel', 'Muraena helena', 'deniz', 'Kayalık oyuklarda saklanan gececi avcıdır.', 'Resif oyukları, mağaralar ve taşlık dipler.', 'Yaz geceleri.', 'Balık parçaları ve dip takımı.', true),
  ('Yılan Balığı', 'European Eel', 'Anguilla anguilla', 'göç', 'Hem tatlı su hem kıyı bağlantılı yaşayan uzun gövdeli türdür.', 'Dere ağızları, sazlıklar ve gece aktif dip alanları.', 'Yaz geceleri ve sonbahar.', 'Canlı yem, kurt ve dip takımı.', true),
  ('Gökkuşağı Alabalığı', 'Rainbow Trout', 'Oncorhynchus mykiss', 'tatlı_su', 'Soğuk tatlı sularda sportif değeri yüksek bir salmoniddir.', 'Alabalık çiftlik çıkışları, serin göller ve akarsular.', 'İlkbahar ve sonbahar.', 'Kaşık, spinner, silikon ve sinek.', true),
  ('Tatlı Su Kefali', 'Chub', 'Squalius cephalus', 'tatlı_su', 'Akarsularda çok yönlü av veren çevik bir türdür.', 'Akarsu kıvrımları, ağaç altları ve kıyı gölgeleri.', 'İlkbahar sonu ve yaz.', 'Küçük kaşık, böcek, ekmek ve silikon.', true),
  ('Kızılkanat', 'Rudd', 'Scardinius erythrophthalmus', 'tatlı_su', 'Sazlık kıyılarda sürü halinde gezen otçul eğilimli balıktır.', 'Göl kenarları, sazlıklar ve yavaş akışlı sular.', 'İlkbahar ve yaz.', 'Ekmek, kurt ve küçük şamandıra takımı.', true),
  ('Kadife Balığı', 'Tench', 'Tinca tinca', 'tatlı_su', 'Dipte beslenen ve sakin sularda yaşayan dayanıklı bir türdür.', 'Bitkili göller, sazlık baraj kıyıları ve çamurlu dipler.', 'Yaz dönemi.', 'Kurt, mısır ve dip yemleri.', true),
  ('Siraz', 'Capoeta', 'Capoeta capoeta', 'tatlı_su', 'Akarsu sistemi içinde güçlü akıntıya uyumlu yaşayan yerli türdür.', 'Akarsu tabanları, taşlı dere yatakları ve baraj girişleri.', 'İlkbahar ve yaz.', 'Hamur, kurt ve akıntı altı takımları.', true),
  ('Bıyıklı Balık', 'Barbel', 'Barbus barbus', 'tatlı_su', 'Dipte gezen ve akıntılı sularda güçlü vuruşlar veren türdür.', 'Taşlık akarsu dipleri ve kanal kenarları.', 'İlkbahar sonu ve yaz.', 'Kurt, hamur ve dip yemleri.', true),
  ('İnci Kefali', 'Pearl Mullet', 'Alburnus tarichi', 'tatlı_su', 'Van Gölü havzasının karakteristik göç eden balığıdır.', 'Göl bağlantılı akarsular ve akıntılı giriş noktaları.', 'İlkbahar göç dönemi.', 'Küçük kaşık ve akıntı takımları.', true),
  ('Tatlı Su Levreği', 'Perch', 'Perca fluviatilis', 'tatlı_su', 'Sürü halinde gezen çizgili bir tatlı su avcısıdır.', 'Göl kıyıları, derinleşen şevler ve sualtı yapıları.', 'İlkbahar ve sonbahar.', 'Jig, küçük silikon ve spinner.', true),
  ('İsrail Sazanı', 'Prussian Carp', 'Carassius gibelio', 'tatlı_su', 'Birçok göl ve barajda görülen dayanıklı bir tatlı su türüdür.', 'Durgun göller, kanallar ve sazlık kıyılar.', 'Yaz ve sonbahar.', 'Hamur, mısır ve şamandıralı takım.', true),
  ('Aynalı Sazan', 'Mirror Carp', 'Cyprinus carpio', 'tatlı_su', 'Sazanın iri pullu kültür formu olarak avcılıkta ayrı anılır.', 'Baraj gölleri, sakin koylar ve yemlenen alanlar.', 'İlkbahar sonu ve yaz.', 'Boilie, mısır ve dip yemleme takımları.', true),
  ('Gümüş Balığı', 'Sand Smelt', 'Atherina boyeri', 'tatlı_su', 'Küçük boylu ama bazı göllerde yoğun sürüler oluşturan türdür.', 'Göl yüzeyi, kıyı çizgisi ve sakin su alanları.', 'Yaz dönemi.', 'Küçük tüy takımları ve mini jigler.', true),
  ('Kızılgöz', 'Roach', 'Rutilus rutilus', 'tatlı_su', 'Sürü gezen ve hassas takım gerektiren sakin su balığıdır.', 'Göller, kanallar ve ağır akıntısız kıyılar.', 'İlkbahar ve yaz.', 'Ekmek, kurt ve küçük şamandıra takımı.', true),
  ('Şabut', 'Mesopotamian Trout Barb', 'Tor grypus', 'tatlı_su', 'Güneydoğu sularında bilinen iri yapılı yerli bir av balığıdır.', 'Büyük nehirler, derin akarsu oyukları ve baraj girişleri.', 'İlkbahar sonu ve sonbahar.', 'Hamur, canlı yem ve ağır akarsu takımları.', true),
  ('Dere Alabalığı', 'Brown Trout', 'Salmo trutta fario', 'tatlı_su', 'Soğuk dere sistemlerinde yaşayan çevik alabalık formudur.', 'Yüksek rakımlı dereler ve oksijenli akışlar.', 'İlkbahar ve sonbahar.', 'Spinner, sinek ve küçük kaşık.', true),
  ('Akbalık', 'Asp', 'Leuciscus aspius', 'tatlı_su', 'Yüzeye yakın avlanan hızlı bir tatlı su yırtıcısıdır.', 'Nehir akıntıları, baraj kuyruk suyu ve geniş akarsular.', 'İlkbahar ve yaz.', 'Metal jig, minnow ve yüzey yemleri.', true),
  ('Havuz Balığı', 'Crucian Carp', 'Carassius carassius', 'tatlı_su', 'Sakin ve sığ sularda yaşayan dirençli bir sazanimsidir.', 'Küçük göletler, sazlık havuzlar ve yavaş su alanları.', 'Yaz dönemi.', 'Hamur, kurt ve küçük dip takımları.', true),
  ('Çapak', 'Common Bream', 'Abramis brama', 'tatlı_su', 'Sürü halinde gezen dipçi yapıda bir göl balığıdır.', 'Baraj gölleri, çamurlu dipler ve derin kıyılar.', 'İlkbahar sonu ve yaz.', 'Hamur, mısır ve yemleme takımları.', true),
  ('Kasna', 'Nase', 'Chondrostoma regium', 'tatlı_su', 'Akarsuda akıntıyı seven yerli otobur-dipçi karakterli türdür.', 'Taşlı nehir yatakları ve orta akıntılı bölgeler.', 'İlkbahar ve yaz.', 'Hamur ve akıntı altı takımları.', true),
  ('Kocaağız', 'Tigris Scraper', 'Capoeta trutta', 'tatlı_su', 'Güneydoğu havzalarında bilinen güçlü akarsu türlerinden biridir.', 'Akıntılı nehirler, taşlık dipler ve bent altları.', 'İlkbahar sonu ve yaz.', 'Hamur, kurt ve dip takımı.', true),
  ('Mersin Balığı', 'Sturgeon', 'Acipenser gueldenstaedtii', 'göç', 'Nadir ve güçlü yapılı göçmen dip balığıdır.', 'Büyük nehir ağızları, kıyı bağlantıları ve dip hatları.', 'İlkbahar göçü.', 'Dip takımı ve doğal yemler.', true),
  ('Camgöz', 'Blue Shark', 'Prionace glauca', 'göç', 'Açık suda dolaşan çevik köpek balığı türlerinden biridir.', 'Pelajik derin sular ve açık deniz akıntıları.', 'Yaz sonu.', 'Büyük yemli takım ve sürükleme.', true),
  ('Vatoz', 'Common Stingray', 'Dasyatis pastinaca', 'deniz', 'Dipte yatan ve güçlü çekiş sağlayan kıkırdaklı türdür.', 'Kumlu dipler, koy içleri ve açık kıyı tabanları.', 'Yaz dönemi.', 'Balık parçası, kalamar ve dip takımı.', true),
  ('Güneş Balığı', 'Pumpkinseed', 'Lepomis gibbosus', 'tatlı_su', 'Küçük gölet ve sazlık alanlarda yaşayan renkli bir türdür.', 'Sığ göletler, sazlık kıyılar ve durgun su alanları.', 'Yaz dönemi.', 'Kurt ve küçük iğneli takım.', true),
  ('Göl Alabalığı', 'Lake Trout', 'Salvelinus namaycush', 'tatlı_su', 'Soğuk ve derin göllerde aranan büyük alabalık tipidir.', 'Derin ve serin göl katmanları.', 'İlkbahar ve sonbahar.', 'Kaşık, trolling takımı ve büyük silikonlar.', true)
on conflict (name_tr) do update set
  name_en = excluded.name_en,
  name_scientific = excluded.name_scientific,
  category = excluded.category,
  description_tr = excluded.description_tr,
  habitat_tr = excluded.habitat_tr,
  best_season_tr = excluded.best_season_tr,
  bait_tr = excluded.bait_tr,
  is_active = excluded.is_active;
