alter table public.catches
  add column if not exists captured_at timestamptz,
  add column if not exists air_temp_c numeric(5,2),
  add column if not exists pressure_hpa integer,
  add column if not exists humidity_pct integer,
  add column if not exists weather_code integer,
  add column if not exists weather_label text,
  add column if not exists wind_speed_kmh integer,
  add column if not exists wind_direction_deg integer,
  add column if not exists wind_direction_label text,
  add column if not exists uv_index numeric(4,1),
  add column if not exists wave_height_m numeric(5,2),
  add column if not exists wave_direction_deg integer,
  add column if not exists sea_temp_c numeric(5,2),
  add column if not exists sea_depth_m numeric(7,2),
  add column if not exists sea_depth_source text,
  add column if not exists sea_depth_is_approximate boolean not null default false,
  add column if not exists moon_phase_label text,
  add column if not exists moon_phase_emoji text,
  add column if not exists fishing_score smallint,
  add column if not exists fishing_score_label text;
